import{i as p,S as m}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const h="47394574-2a816324e728e13b0469414a4",f="https://pixabay.com/api/",y=async t=>{const o=`${f}?key=${h}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true`;try{const n=await fetch(o);if(!n.ok)throw new Error("Something went wrong with the API request.");return(await n.json()).hits}catch(n){throw console.error(n),n}},g=t=>{const o=document.querySelector(".gallery");if(o.innerHTML="",t.length===0){p.error({title:"Sorry",message:"There are no images matching your search query. Please try again!",position:"top-center"});return}t.forEach(({webformatURL:s,largeImageURL:e,tags:r,likes:i,views:l,comments:d,downloads:u})=>{const a=document.createElement("div");a.classList.add("gallery-item"),a.innerHTML=`
      <a href="${e}" class="gallery-link">
        <img src="${s}" alt="${r}" class="gallery-image"/>
        <div class="info">
          <p><b>Likes:</b> ${i}</p>
          <p><b>Views:</b> ${l}</p>
          <p><b>Comments:</b> ${d}</p>
          <p><b>Downloads:</b> ${u}</p>
        </div>
      </a>
    `,o.appendChild(a)}),new m(".gallery a").refresh()},b=()=>{const t=document.querySelector(".loader");t.style.display="block"},w=()=>{const t=document.querySelector(".loader");t.style.display="none"},L=document.querySelector("#search-form"),c=document.querySelector("#search-input");L.addEventListener("submit",async t=>{t.preventDefault();const o=c.value.trim();if(o===""){iziToast.error({title:"Error",message:"Please enter a search term.",position:"top-center"});return}b();try{const n=await y(o);g(n)}catch{iziToast.error({title:"Error",message:"An error occurred while fetching images.",position:"top-center"})}finally{w()}c.value=""});
//# sourceMappingURL=index.js.map
