import{i as d,S as p}from"./assets/vendor-5ObWk2rO.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const g=r=>{const n=document.querySelector(".gallery");if(n.innerHTML="",!Array.isArray(r)||r.length===0){d.error({title:"Sorry",message:"There are no images matching your search query. Please try again!",position:"topCenter"});return}r.forEach(({webformatURL:i,largeImageURL:e,tags:o,likes:s,views:h,comments:y,downloads:m})=>{const a=document.createElement("div");a.classList.add("gallery-item"),a.innerHTML=`
      <a href="${e}" class="gallery-link">
        <img src="${i}" alt="${o}" class="gallery-image"/>
        <div class="info">
          <p><b>Likes:</b> ${s}</p>
          <p><b>Views:</b> ${h}</p>
          <p><b>Comments:</b> ${y}</p>
          <p><b>Downloads:</b> ${m}</p>
        </div>
      </a>
    `,n.appendChild(a)}),new p(".gallery a").refresh()},u=()=>{const r=document.querySelector(".loader");r?r.style.display="block":console.error("Loading indicator not found.")},f=()=>{const r=document.querySelector(".loader");r?setTimeout(()=>{r.style.display="none"},500):console.error("Loading indicator not found.")},b="47394574-2a816324e728e13b0469414a4",w="https://pixabay.com/api/",L=async r=>{const n=`${w}?key=${b}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true`;try{u();const t=await fetch(n);if(!t.ok)throw new Error("Something went wrong with the API request.");return(await t.json()).hits}catch(t){throw alert(`Error: ${t.message}`),console.error(t),t}finally{f()}},q=document.querySelector("#search-form"),l=document.querySelector("#search-input"),c=r=>{d.error({title:"Error",message:r,position:"topCenter"})};q.addEventListener("submit",async r=>{r.preventDefault();const n=l.value.trim();if(n===""){c("Please enter a search term.");return}u();try{const t=await L(n);t.length===0?c("There are no images matching your search query. Please try again!"):g(t)}catch{c("An error occurred while fetching images.")}finally{f()}l.value=""});
//# sourceMappingURL=index.js.map
